### ISSUE TITLE
Opening mrc file cause world2colorMatrix error when running on local pc

### ISSUE THREAD

**Issue by sowacx** [epam/miew#417]
Helllo,
Your demo app available at: https://miew.opensource.epam.com/ is opening mrc file easily, e.g. https://ftp.ebi.ac.uk/pub/databases/emtest/fsc_mapsuite/groel/groel_stagg_map2.mrc

But when I'm building demo file or run some example (e.g. "Use Miew via Require.js") it keeps me getting errors like: 
![image](https://user-images.githubusercontent.com/1485449/176896094-dd0c2de6-0c7f-4ca0-b742-3539815b2bc2.png)
![image](https://user-images.githubusercontent.com/1485449/176896255-942bdb30-cbf3-49b8-b032-1ade8f86a075.png)

I was trying with master and latest tag same issue. Also using min file from https://github.com/epam/miew/blob/master/packages/miew/dist/miew.min.js didn't helped. Do you have any idea what is causing that issue?

**Comment by ag-deepesh** [comment]
Hi @AnaMoskvina, 

I also faced the same error. Any suggestions/comments to resolve the above error?

**Comment by paulsmirnov** [comment]
Hi @ag-deepesh and @sowacx, the version accessible at https://miew.app/ or https://miew.opensource.epam.com/ is 0.9.0 (built in Dec 2020). If you wish to reproduce the old behavior locally you could checkout the corresponding tag. The latest master is not released yet.

**Comment by paulsmirnov** [comment]
I'll log here intermediate results.

The latest working commit is 25cc042.

The commit 410e92d (upgrade three.js) breaks the entire rendering:
```plain
TypeError: Cannot read properties of undefined (reading 'length')
    at UberMaterial.copy (http://localhost:8080/vendor.72e2d5422868a8e54e90.js:34321:1415)
    at UberMaterial.copy (http://localhost:8080/vendor.72e2d5422868a8e54e90.js:34464:699)
    at push.QKg8.UberMaterial.copy (http://localhost:8080/demo.6f8b109d17b8c503ac32.js:29179:74)
    at push.QKg8.UberMaterial.createInstance (http://localhost:8080/demo.6f8b109d17b8c503ac32.js:29216:8)
    at new TransformGroup (http://localhost:8080/demo.6f8b109d17b8c503ac32.js:44507:24)
    at new ChemGroup (http://localhost:8080/demo.6f8b109d17b8c503ac32.js:33034:19)
    at ResiduesSubseqGroup._createSuperInternal (http://localhost:8080/demo.6f8b109d17b8c503ac32.js:45222:405)
    at new ResiduesGroup (http://localhost:8080/demo.6f8b109d17b8c503ac32.js:45236:19)
    at ResiduesSubseqGroup._createSuperInternal (http://localhost:8080/demo.6f8b109d17b8c503ac32.js:20984:405)
    at new ResiduesSubseqGroup (http://localhost:8080/demo.6f8b109d17b8c503ac32.js:21044:19)
```

The commit ba59b11 fixes this and some other issues, but the volumetric rendering error gets unnoticed:
```plain
TypeError: Cannot read properties of undefined (reading 'world2colorMatrix')
    at Miew._renderVolume (http://localhost:8080/demo.55f16a9802bbea1aadea.js:7904:94)
    at Miew._renderScene (http://localhost:8080/demo.55f16a9802bbea1aadea.js:7649:12)
    at Miew._renderFrame (http://localhost:8080/demo.55f16a9802bbea1aadea.js:7452:14)
    at push.57ka.Miew._onRender (http://localhost:8080/demo.55f16a9802bbea1aadea.js:7416:8)
    at push.57ka.Miew._onTick (http://localhost:8080/demo.55f16a9802bbea1aadea.js:7277:10)
    at http://localhost:8080/demo.55f16a9802bbea1aadea.js:7271:19
```
